# Generated by Django 4.1.4 on 2023-01-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
                ('song', models.FileField(upload_to='audio_files')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.singer')),
            ],
        ),
        migrations.CreateModel(
            name='album',
            fields=[
                ('album_name', models.CharField(max_length=1000)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='music.singer')),
                ('song100', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song10', to='music.song')),
                ('song11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('song22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song2', to='music.song')),
                ('song33', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song3', to='music.song')),
                ('song44', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song4', to='music.song')),
                ('song55', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song5', to='music.song')),
                ('song66', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song6', to='music.song')),
                ('song77', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song7', to='music.song')),
                ('song88', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song8', to='music.song')),
                ('song99', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song_song9', to='music.song')),
            ],
        ),
    ]
