# Generated by Django 4.1.4 on 2023-01-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
