# Generated by Django 4.1.4 on 2023-01-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
    ]
