# Generated by Django 4.1.4 on 2023-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_album_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
