# Generated by Django 4.1.4 on 2023-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_album_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('podcaster', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=10000)),
                ('audio', models.FileField(upload_to='audio_files')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
